### ISSUE TITLE
AWS CloudFormation Template

### ISSUE THREAD

**Issue by amandiobm** [crewjam/etcd-aws#20]
Hi guys, 

I read all the blog post and I loved the solution. But I'm having some problems to get de AWS CloudFormation Template. I'm not a Go developer, and I don't know even start to build this. But I really really need this solution. Is possible to someone send me this etcd.template?

Best regards.

TKS!

**Comment by amandiobm** [comment]
I managed to get the template :muscle:

After created the stack. How I access the etcd?

For example from postman? Which is the host?

Best regards,

**Comment by armandoisaac** [comment]
Hello!

Was wondering how did you managed to run this as I've been struggling for days without success or if you can provide an example of the output template it generates.

Really appreciated!

**Comment by amandiobm** [comment]
Ohhh, I'll try to run again, and documented all my steps. 
But on the last time, I got a success from the aws cloud formation, but I could not access the etcd from his API.

Let`s try it to do together.

**Comment by xbox1994** [comment]
@armandoisaac you can get it from https://github.com/xbox1994/etcd-cloudformation-template
