### ISSUE TITLE
Flocker

### ISSUE THREAD

**Issue by jogster** [crewjam/etcd-aws#3]
Hi, love your work -- didn't realise it was possible to save/restore the state of etcd and start up without a discovery token.

I have a similar requirement to get a HA CoreOS cluster working in AWS, I had been apprehensive about the cluster getting damaged during a catastrophic reboot.

Having understood what you are doing, have you considered Flocker?

Since you are running the etcd_aws in a docker you will get the load/save into an EBS volume. Don't know if it will make much difference to your design but it removes the need for a named S3 bucket....

**Comment by crewjam** [comment]
Thanks for the feedback. 

For backups, the core issue is that the built-in backup provided by etcd includes both the data stored **and** the cluster state. If you have a complete failure of the cluster -- I think you don't want the cluster state restored. 

In other words, the problem with built-in backup isn't **how** it is stored, it is **what** is stored.

After that, the question is where to store the backups, and S3 seems like a logical place, but that isn't essential to the approach.

Hope that helps and thanks for your comment!

**Comment by jogster** [comment]
Yes it does help me. I currently been playing with local coreos clusters (created 10 - 5 masters/5 slaves) but had noticed instability a few times, especially when trying to replace a master. I am using etcd as my bootstrap kv, then running consul against that and using zookeeper to power my mesos cluster.

Makes me think that I probably need to save consul and zookeeper as they all help to bootstrap the cluster.

I do not have a huge experience with go-lang (at the moment) but was wondering if there was a possibility of reading/writing the data for etcd_aws from a mounted share?

This is so that I can test it locally on my mac with vagrant (it exposes a mount into the machine) and get a good understanding before trying to grapple with it on AWS.
