### ISSUE TITLE
ResourceSignal timeout

### ISSUE THREAD

**Issue by pboguk** [crewjam/etcd-aws#5]
Hi,
Seems 5 minutes for
  "MasterAutoscale": {
      "Type": "AWS::AutoScaling::AutoScalingGroup",
      "CreationPolicy": {
        "ResourceSignal": {
          "Count": 3,
          "Timeout": "PT5M"
        }
      },
not enough. Deployment stops.

When change to 10 - ok.
Here's example:

```
14:38:32 UTC+0300   CREATE_IN_PROGRESS  AWS::AutoScaling::AutoScalingGroup  MasterAutoscale     Received SUCCESS signal with UniqueId i-df0b7058
Physical ID:CF23-ETCD-PBOGUK-STACK-MasterAutoscale-4N1QTY021CQU
14:32:59 UTC+0300   CREATE_IN_PROGRESS  AWS::AutoScaling::AutoScalingGroup  MasterAutoscale     Received SUCCESS signal with UniqueId i-d3106b54
Physical ID:CF23-ETCD-PBOGUK-STACK-MasterAutoscale-4N1QTY021CQU
14:32:38 UTC+0300   CREATE_IN_PROGRESS  AWS::AutoScaling::AutoScalingGroup  MasterAutoscale     Received SUCCESS signal with UniqueId i-b657a42c
```

As you can see difference 14:38:32 and 14:32:59 more than 5 minutes.
I made about 10 attempts and results are quite similar.

FYI

**Comment by crewjam** [comment]
So you are saying the value should be `PT10M`?  That seems reasonable.  Want to do a pull request?

**Comment by pboguk** [comment]
With PT10M stack completes with success.

**Comment by pboguk** [comment]
It was an AWS issue.
Closed.
